# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_review:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # docker 镜像缓存
      - name: docker for influxdb & grafana
        run: |
            sudo docker pull grafana/grafana
            sudo docker pull influxdb:1.8.3
            
             sudo docker run -d \
             -p 8083:8083 \
             -p 8086:8086 \
             --name influxdb \
             -v /home/runner/work/lmp/lmp/test/influxdb_config/default.conf:/etc/influxdb/influxdb.conf \
             -v /home/runner/work/lmp/lmp/test/influxdb_config/data:/var/lib/influxdb/data \
             -v /home/runner/work/lmp/lmp/test/influxdb_config/meta:/var/lib/influxdb/meta \
             -v /home/runner/work/lmp/lmp/test/influxdb_config/wal:/var/lib/influxdb/wal influxdb:1.8.3
      # python 
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
     
      - name: Install dependencies
        run: |
          sudo /usr/bin/python3 -m pip install --upgrade pip
          sudo /usr/bin/python3 -m pip install influxdb
          sudo /usr/bin/python3 -m pip install --ignore-installed PyYAML
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # bcc
      - name: Install bcc
        run: |
          sudo apt-get update
          sudo apt-get -y install bison build-essential cmake flex git libedit-dev libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev libfl-dev
          git clone https://github.com/iovisor/bcc.git
          mkdir bcc/build; cd bcc/build
          cmake ..
          make
          sudo make install
          cmake -DPYTHON_CMD=python3 .. # build python3 binding
          pushd src/python/
          make
          sudo make install
          popd

      # test
      - name: Test plugins
        run: |
          sudo python3 plugins/cpuutilize.py
      
      
      # go
      
      # docker
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        
